import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Authlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Center auth pages without affecting the global layout.
  // Use viewport units so it fills the screen even though the root body is a flex container.
  // Avoid nesting <main> inside the root <main> for valid semantics.
  return (
    <div className="w-screen min-h-dvh flex items-center justify-center px-4">
      <div className="w-full max-w-md">
        {children}
      </div>
    </div>
  );
}