import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalSidebar from "@/components/Sidebar/ConditionalSidebar";
import AuthGuard from "@/components/AuthGuard/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex overflow-x-hidden`}
      >
        <AuthGuard>
          <ConditionalSidebar />
          <main className="flex-1 overflow-auto">
            {children}
          </main>
        </AuthGuard>
      </body>
    </html>
  );
}
